[build]
builder = "nixpacks"

[deploy]
startCommand = "npm install && npm run build && node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "8080"
MEMORY_FILE_PATH = "/app/data/project-memory.json"
SESSIONS_FILE_PATH = "/app/data/project-sessions.json"
